---

variables:
  project: '$CI_PROJECT_NAME'
  lxc: 'job$CI_JOB_ID'

before_script:
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

  # Create .lxdock.yml
  - |
    echo """
    name: $project

    containers:
      - name: $lxc
        image: ubuntu/xenial
        hostnames:
          - $lxc

    provisioning:
      - type: ansible
        playbook: tests/test.yml
    """ > .lxdock.yml

  - cat .lxdock.yml

AnsibleRoleCheck:
  script:
    # Basic role syntax check
    - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

    # Deploy lxdock project and run the role/playbook
    - lxdock up

    # Run the role/playbook again, checking to make sure it's idempotent
    - >
      lxdock provision
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)

    # Check for role is done
    - lxdock shell $lxc -c mysql -u dbuser -pdbpasswd -e "show databases"
    - lxdock shell $lxc -c mysql -u dbuser -pdbpasswd -e "SHOW GRANTS FOR 'dbuser'@'localhost'"
    
after_script:
  - lxdock destroy -f
